<h2>Formulaire d’inscription</h2>

<div class="row">
    <div class="col-md-12">
        <form method="post" action="<?php echo $this->url('register', array('action' => 'submit')); ?>">
            <fieldset><legend>Informations d’identification</legend>
                <label for="username">Nom d’utilisateur</label>
                <input id="username" name="username" type="text" required="required" />

                <label for="password">Mot de passe</label>
                <input id="password" name="password" type="password" required="required" />
                
                <label for="passwordbis">Mot de passe (répétez)</label>
                <input id="passwordbis" name="passwordbis" type="password" required="required" />
            </fieldset>
            <fieldset><legend>Informations de contact</legend>
                <label for="email">Adresse email</label>
                <input id="email" name="email" type="text" required="required" />
            </fieldset>
            <input type="submit" value="Envoyer" />
        </form>
    </div>
</div>
