<h2><?php echo $title; ?></h2>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><a href="">Dernier billet</a> <a class="pull-right" href="#">par Zeldren</a></h3>
    </div>
    <div class="panel-body">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus...</p>
        <p><a class="btn btn-success pull-right" href="">Lire la suite &raquo;</a></p>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><a href="">Avant-dernier billet</a> <a class="pull-right" href="#">par Zeldren</a></h3>
    </div>
    <div class="panel-body">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a diam lectus...</p>
        <p><a class="btn btn-success pull-right" href="">Lire la suite &raquo;</a></p>
    </div>
</div>

<div class="text-center">
    <ul class="pagination">
        <li class="disabled"><a href="#">&laquo;</a></li>
        <li class="active"><a href="#">1</a></li>
        <li><a href="">2</a></li>
        <li><a href="">…</a></li>
        <li><a href="">9</a></li>
        <li><a href="">10</a></li>
        <li><a href="">&raquo;</a></li>
    </ul>
</div>