<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            <strong><?php echo $post->getTitle(); ?></strong>
            <span class="pull-right">par <strong><?php echo $post->getAuthorId()->getUsername(); ?></strong></span>
        </h3>
    </div>
    <div class="panel-body">
        <p><?php echo nl2br($post->getContent()); ?>
        <?php
        if($post->getDateCreate() != $post->getDateEdit()) {
            ?>
            <p><em>Dernière modification le <?php echo $post->getDateEdit()->format('d\/m\/Y\ \à\ H\:i'); ?></em></p>
                <?php
                if ($post->getAuthorId()->getUsername() == $this->zfcUserDisplayName()) {
                ?>
                    <p>
                        <span class="pull-left">
                            <a><span class="glyphicon glyphicon-star"></span></a>
                            <a><span class="glyphicon glyphicon-star"></span></a>
                            <a><span class="glyphicon glyphicon-star"></span></a>
                            <a><span class="glyphicon glyphicon-star"></span></a>
                            <a><span class="glyphicon glyphicon-star"></span></a>
                        </span>
                        <?php 
                        echo '<a class="btn glyphicon glyphicon-remove pull-right" title="Supprimer" href="'.$this->url('post-crud', array('action' => 'delete','pid' => $post->getId())).'"></a>';
                        echo '<a class="btn glyphicon glyphicon-pencil pull-right" title="Éditer" href="'.$this->url('post-crud', array('action' => 'update','pid' => $post->getId())).'"></a>'
                        ?>
                    </p>
            <?php
                }
        }
        ?>
    </div>
    <div class="panel-footer">
        <p class="panel-title">
            <span class="zf-green">Posté le <?php echo $post->getDateCreate()->format('d\/m\/Y\ \à\ H\:i'); ?></span>
            <img class="pull-right" src="<?php echo $this->basePath('img/zf2-logo.png'); ?>" alt="ZF2" />
        </p>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Commentaires (<?php echo $nb_comment; ?>)</h3>
    </div>
    <div class="panel-body">
        <table class="table table-bordered">
        <?php 
        if($nb_comment == 0) { 
            ?>
                <tbody><tr><td>Pas de commentaire</td></tr></tbody>
            </table>
            <?php
        }
        else {
            ?>
            <thead>
                <tr style="background-color: #68b604 ; color: white">
                    <th style="width: 120px">Pseudo</th>
                    <th>Commentaire</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach($this->comment as $comm) {
                    ?>
                    <tr>
                        <td class="text-center"><?php echo $this->gravatar($comm['author']['email'])->setImgSize(100); ?></td>
                        <td><?php echo nl2br($comm['content']);
                            if ($comm['author'] == $this->zfcUserDisplayName()) {
                            ?>
                            <p>
                                <?php 
                                echo '<a class="btn glyphicon glyphicon-remove pull-right" title="Supprimer" href="'.$this->url('comment', array('action' => 'delete','cid' => $comm['id'])).'"></a>';
                                echo '<a class="btn glyphicon glyphicon-pencil pull-right" title="Éditer" href="'.$this->url('comment', array('action' => 'update','cid' => $comm['id'])).'"></a>'
                                ?>
                            </p>
                            <?php }
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-center" style="border-top:#FFFFFF;"><strong><?php echo $comm['author']['username']; ?></strong></td>
                        <td><span class="zf-green">Posté le <?php echo $comm['date_create']->format('d\/m\/Y\ \à\ H\:i'); ?></span></td>
                    
                    </tr>
                    <?php
                 } //foreach
                ?>
                </tbody>
            </table>
            <?php 
                if($nb_comment > 5) { 
            ?>
            <div class="text-center">
                <ul class="pagination">
                    <?php
                    // Page précédente
                    if($this->page == 1) {
                        echo '<li class="disabled"><a href="#">&laquo;</a></li>';
                    }
                    else {
                        echo '<li><a href="'.$this->url('post-view', array('page' => ($this->page - 1))).'">&laquo;</a></li>';
                    }

                    // Liste des pages
                    for($i = 1; $i <= $nb_pages; ++$i) {
                        echo '<li'.(($i == $this->page) ? ' class="active"' : '').'>'
                           . '<a href="'.$this->url('post-view', array('page' => $i)).'">'.$i.'</a>'
                           . '</li>';
                    }

                    // Page suivante
                    if($this->page == $this->nb_pages) {
                        echo '<li class="disabled"><a href="#">&raquo;</a></li>';
                    }
                    else {
                        echo '<li><a href="'.$this->url('post-view', array('page' => ($this->page + 1))).'">&raquo;</a></li>';
                    }
                    ?>
                </ul>
            </div>
        <?php
            }
        } // else
        ?>
    </div>
    <div class="panel-footer">
        <p class="text-center" style="margin: 0px;"><a class="btn btn-success" style="margin: 0px;" href="<?php echo $this->url('comment', array('action' => 'create')); ?>">Poster un commentaire</a></p>
    </div>
</div>