<h3><?php echo $this->layout()->title; ?></h3>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            <strong>Titre du billet</strong>
            <span class="pull-right">par <strong>Zeldren</strong></span>
        </h3>
    </div>
    <div class="panel-body">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p><em>Dernière modification le <?php echo date('d/m/Y') ?> à <?php echo date('H:NN') ?></em></p>
    </div>
    <div class="panel-footer">
        <p class="panel-title"><span class="zf-green">Posté le <?php echo date('d/m/Y') ?> à <?php echo date('H:NN') ?></span><img class="pull-right" src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="ZF2" /></p>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Commentaires (2)</h3>
    </div>
    <div class="panel-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="width: 170px">Pseudo</th>
                    <th>Commentaire</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><strong>julien.papasian</strong></td>
                    <td>Posté le <?php echo date('d/m/Y') ?> à <?php echo date('H:NN') ?></td>
                </tr>
                <tr>
                    <td><img src="http://www.gravatar.com/avatar/e78ffb90e799b023e93aa1ea2f568558?s=150&d=mm&r=g" alt="" /></td>
                    <td>Commentaire1</td>
                </tr>
                <tr>
                    <td><strong>m.brenguier</strong></td>
                    <td>Posté le <?php echo date('d/m/Y') ?> à <?php echo date('H:NN') ?></td>
                </tr>
                <tr>
                    <td><img src="http://www.gravatar.com/avatar/805da4864c506f7a6f0c6a236553e8ce?s=150&d=mm&r=g" alt="" /></td>
                    <td>Commentaire2</td>
                </tr>
            </tbody>
        </table>

        <div class="text-center">
            <ul class="pagination">
                <li class="disabled"><a href="#">&laquo;</a></li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="">2</a></li>
                <li><a href="">…</a></li>
                <li><a href="">9</a></li>
                <li><a href="">10</a></li>
                <li><a href="">&raquo;</a></li>
            </ul>
        </div>
    </div>
    <div class="panel-footer">
        <!--TODO : formulaire d'ajout de commentaires -->
    </div>
</div>