<h2>Se connecter</h2>

<div class="row">
    <div class="col-md-12">
        <form method="post" action="<?php echo $this->url('login', array('action' => 'submit')); ?>" class="form-horizontal" role="form">
            <fieldset><legend>Informations d’identification</legend>
                <div class="form-group">
                    <label for="username" class="col-sm-2 control-label">Nom d’utilisateur</label>
                    <div class="col-sm-10">
                        <input class="form-control" id="username" name="username" type="text" required="required" />
                    </div>
                </div>

                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">Mot de passe</label>
                    <div class="col-sm-10">
                        <input class="form-control" id="password" name="password" type="password" required="required" />
                    </div>
                </div>
            </fieldset>
            <div class="form-group">
               <div class="col-sm-offset-2 col-sm-10">
                  <input class="btn btn-default" type="submit" value="Envoyer" />
               </div>
            </div>
        </form>
    </div>
</div>
