<?php echo $this->doctype(); ?>

<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle('ZF2 Blog App')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;ZF2 Blog App</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <!-- TODO: N’afficher que si pas connecté -->
                        <?php
                        if(!$this->zfcUserIdentity()) {
                            ?>
                            <li><a href="<?php echo $this->url('zfcuser/register'); ?>">S’inscrire</a></li>
                            <li><a href="<?php echo $this->url('zfcuser/login'); ?>">Se connecter</a></li>                        
                            <?php
                        }
                        else {
                            ?>
                            <li class="dropdown">
                                <a href="<?php echo $this->url('zfcuser'); ?>" class="dropdown-toggle" data-toggle="dropdown"> <?php echo $this->gravatar($this->zfcUserIdentity()->getEmail())->setImgSize(22); ?>&nbsp;&nbsp;Mon compte</a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url('zfcuser'); ?>"> Mon compte</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->url('zfcuser/changepassword'); ?>">Modifier le mot de passe</a></li>
                                    <li><a href="<?php echo $this->url('zfcuser/changeemail'); ?>">Modifier l’email</a></li>
                                </ul>
                            </li>
                            <li><a href="<?php echo $this->url('zfcuser/logout'); ?>">Se déconnecter</a></li>
                            <?php
                        }
                        ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
