<?php echo $this->doctype(); ?>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle('ZF2 Blog App')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon2.ico')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;ZF2 Blog App</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <?php
                        if(!$this->zfcUserIdentity()) {
                            ?>
                            <li><a href="<?php echo $this->url('zfcuser/register'); ?>">S’inscrire</a></li>
                            <li><a href="<?php echo $this->url('zfcuser/login'); ?>">Se connecter</a></li>                        
                            <?php
                        }
                        else {
                            ?>
                            <li class="dropdown">
                                <a href="<?php echo $this->url('zfcuser'); ?>" class="dropdown-toggle" data-toggle="dropdown"> <?php echo $this->gravatar($this->zfcUserIdentity()->getEmail())->setImgSize(22); ?>&nbsp;&nbsp;Mon compte</a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url('zfcuser'); ?>">Mon compte</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->url('zfcuser/changepassword'); ?>">Modifier le mot de passe</a></li>
                                    <li><a href="<?php echo $this->url('zfcuser/changeemail'); ?>">Modifier l’email</a></li>
                                </ul>
                            </li>
                            <li><a href="<?php echo $this->url('zfcuser/logout'); ?>">Se déconnecter</a></li>
                            <?php
                        }
                        ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <hr />
            <div class="row">
                <div class="col-md-8">
                    <?php echo $this->content; ?>
                </div>

                <div class="col-md-4">
                    <?php
                    if($this->zfcUserIdentity()) {
                        ?>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">Mon compte</h3>
                            </div>
                            <div class="panel-body">
                                    <p class="text-center"><b><?php echo $this->zfcUserDisplayName(); ?></b></p>
                                    <p class="text-center"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail())->setImgSize(124); ?></p>
                                    <p class="text-center"><a class="btn btn-success" href="<?php echo $this->url('post-crud', array('action' => 'create')); ?>">Ajouter un billet</a></p>
                            </div>
                        </div>
                        <?php
                    }
                    else {
                        echo $this->zfcUserLoginWidget();
                    }
                    ?>
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <h3 class="panel-title">Menu</h3>
                        </div>
                        <div class="panel-body">
                            <h3>Recherche</h3>
                            <form class="form-inline" method="post" action="<?php echo $this->url('search'); ?>" role="form">
                                <div class="form-group">
                                    <input id="tag" size="20" class="form-control" name="tag" type="text" placeholder="Recherche…" />
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="OK" class="btn btn-default" />
                                </div>
                            </form>
                            <hr />

                            <!-- Exemples de tags, TODO: à générer -->
                            <h3>Tags populaires</h3>
                            <p>
                                <?php
                                foreach($this->layout()->tags as $tag) {
                                    ?>
                                    <a href="<?php echo $this->url('search', array('tag' => $tag['name'])); ?>"><?php echo $tag['name']; ?></a>
                                    <?php
                                }
                                ?>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <hr />
            <footer>
                <div class="container">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <span class="text-center" style="font-family: Verdana">
                                    <div class="alert alert-success" style="margin : 0px;">
                                        <p>
                                            Projet d'année Licence 3 Informatique IUP MIAGE par Maxime BRENGUIER, Raphaël CANOVAS et Julien PAPASIAN
                                        </p>
                                        <p>
                                            Encadrés par Etienne COLONDON et Émilien ESCALLE
                                        </p>
                                        <p>
                                            <strong>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></strong>
                                        </p>
                                    </div>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>