<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $title; ?></h3>
    </div>
    <div class="panel-body" style="padding: 0 30px">
        <?php
        if($this->isValid === true)
        { 
            ?>
            <div class="alert alert-success">Commentaire ajouté avec succès.</div>
            <?php
        }
        else {
            if(!empty($this->error)) echo $this->alert($this->error, 'alert-error', false);
            echo $this->form($this->form);
        }
        ?>
    </div>
</div>