<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $title; ?></h3>
    </div>
    <div class="panel-body" style="padding: 30px">
        <p class ="text-center">
            <strong>Êtes-vous sur de vouloir supprimer ce commentaire ?</strong>
        </p>
        <p class ="text-center">
            <a class="btn btn-success" href="#" title="Supprimer votre billet">Oui</a>
            <a class="btn btn-danger" href="#" title="Annuler">Non</a>
        </p>
    </div>
</div>