<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $title; ?></h3>
    </div>
    <div class="panel-body" style="padding: 30px">
        <?php
        if($isValid)
        {
            ?>
            <div class="alert alert-info">Commentaire supprimé avec succès.</div>
            <?php
        }
        else
        {
            ?>
            <p class="text-center">
                <strong>Êtes-vous sûr-e de vouloir supprimer ce commentaire ?</strong>
            </p>
            <p class="text-center">
                <a class="btn btn-danger" href="<?php echo $this->url('comm-ud', array('action' => 'delete', 'cid' => $cid, 'sur' => true)); ?>" title="Supprimer ce commentaire">Oui</a>
                <a class="btn btn-success" href="<?php echo $this->url('post-view', array('pid' => $comm->getPost()->getId())); ?>" title="Annuler">Non</a>
            </p>
            <?php
        }
        ?>
    </div>
</div>