<?php
use \Michelf\Markdown;

if(!$post)
{
    ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                Recherche
            </h3>
        </div>
        <div class="panel-body">
            <p>Votre recherche n’a donné aucun résultat.</p>
            <hr />
            <h3>Réessayez</h3>
            <form class="form-inline" method="post" action="<?php echo $this->url('search'); ?>" role="form">
                <div class="form-group">
                    <input id="tag" size="70" class="form-control" name="tag" type="text" placeholder="Recherche…" />
                </div>
                <div class="form-group">
                    <input type="submit" value="OK" class="btn btn-default" />
                </div>
            </form>
            
            <div class="alert alert-warning" style="margin-top: 10px;">
                <strong>Conseils pour votre recherche&nbsp;:</strong>
                <ul>
                    <li>N’utilisez que les mots clés existants (menu de droite).</li>
                    <li>Évitez les combinaisons de mots clés.</li>
                </ul>
            </div>
        </div>
    </div>
    <?php
}
else
{
    foreach($post as $p)
    {     
        ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <a href="<?php echo $this->url('post-view', array('pid' => $p->getId())); ?>"><?php echo $p->getTitle(); ?></a>
                    <span class="pull-right">par <strong><?php echo $p->getAuthor()->getUsername(); ?></strong></span>
                </h3>
            </div>
            <div class="panel-body">
                <p>
                    <?php
                    if(strlen($p->getContent()) > 300) echo Markdown::defaultTransform(substr($p->getContent(), 0, 300).'[…]');
                    else echo Markdown::defaultTransform($p->getContent());
                    ?>
                </p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('post-view', array('pid' => $p->getId())); ?>">Lire la suite &raquo;</a></p>
            </div>
            <div class="panel-footer">
                <p class="panel-title"><span class="zf-green">Posté le <?php echo $p->getDateCreate()->format('d\/m\/Y\ \à\ H\:i'); ?></span><img class="pull-right" src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="ZF2" /></p>
            </div>
        </div>
        <?php
    }
    ?>

    <div class="text-center">
        <ul class="pagination">
            <?php
            // Page précédente
            if($page == 1) {
                echo '<li class="disabled"><a href="#">&laquo;</a></li>';
            }
            else {
                echo '<li><a href="'.$this->url('home', array('page' => ($page - 1))).'">&laquo;</a></li>';
            }

            // Liste des pages
            for($i = 1; $i <= $nb_pages; ++$i) {
                echo '<li'.(($i == $page) ? ' class="active"' : '').'>'
                   . '<a href="'.$this->url('home', array('page' => $i)).'">'.$i.'</a>'
                   . '</li>';
            }

            // Page suivante
            if($page == $nb_pages) {
                echo '<li class="disabled"><a href="#">&raquo;</a></li>';
            }
            else {
                echo '<li><a href="'.$this->url('home', array('page' => ($page + 1))).'">&raquo;</a></li>';
            }
            ?>
        </ul>
    </div>
    <?php
}