        <?php 
        foreach($this->post as $post)
        {     
            ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <a href="<?php echo $this->url('post', array('action' => 'view', 'pid' => $post['id'])); ?>"><?php echo $post['title']; ?></a>
                        <span class="pull-right">par <strong><?php echo $post['author']['username']; ?></strong></span>
                    </h3>
                </div>
                <div class="panel-body">
                    <p>
                        <?php
                        if(strlen($post['content']) > 300) echo nl2br(substr($post['content'], 0, 300)).' […]';
                        else echo nl2br($post['content']);
                        ?>
                    </p>
                    <p><a class="btn btn-success pull-right" href="<?php echo $this->url('post', array('action' => 'view', 'pid' => $post['id'])); ?>">Lire la suite &raquo;</a></p>
                </div>
                <div class="panel-footer">
                    <p class="panel-title"><span class="zf-green">Posté le <?php $date = $post['date_create']; echo $date->format('d\/m\/Y\ \à\ H\:i'); ?></span><img class="pull-right" src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="ZF2" /></p>
                </div>
            </div>
            <?php
        }
        ?>

        <div class="text-center">
            <ul class="pagination">
                <?php
                // Page précédente
                if($this->page == 1) {
                    echo '<li class="disabled"><a href="#">&laquo;</a></li>';
                }
                else {
                    echo '<li><a href="'.$this->url('home', array('page' => ($this->page - 1))).'">&laquo;</a></li>';
                }

                // Liste des pages
                for($i = 1; $i <= $nb_pages; ++$i) {
                    echo '<li'.(($i == $this->page) ? ' class="active"' : '').'>'
                       . '<a href="'.$this->url('home', array('page' => $i)).'">'.$i.'</a>'
                       . '</li>';
                }

                // Page suivante
                if($this->page == $this->nb_pages) {
                    echo '<li class="disabled"><a href="#">&raquo;</a></li>';
                }
                else {
                    echo '<li><a href="'.$this->url('home', array('page' => ($this->page + 1))).'">&raquo;</a></li>';
                }
                ?>
            </ul>
        </div>